// JARVIS — Debug Agent Edge Function
// Runs hourly via pg_cron. Monitors jarvis_errors table.
// When 5+ new errors found: creates briefing, writes report to Obsidian.
// Sandbox-first: NEVER auto-deploys fixes. Logs findings for human review.

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const cors = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') return new Response('ok', { headers: cors });

  try {
    const supabaseUrl = Deno.env.get('SUPABASE_URL') || '';
    const supabaseKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') || '';
    const anthropicKey = Deno.env.get('ANTHROPIC_KEY') || '';

    const body = await req.json().catch(() => ({}));
    const threshold = body.error_threshold || 5;
    const notify = body.notify || ['briefing', 'obsidian'];
    const force = body.force || false;

    const supa = createClient(supabaseUrl, supabaseKey);

    // Check errors in last hour (or last 24h if forced from UI)
    const since = new Date(Date.now() - (force ? 86400000 : 3600000)).toISOString();
    const { data: errors, count } = await supa
      .from('jarvis_errors')
      .select('*', { count: 'exact' })
      .gte('created_at', since)
      .order('created_at', { ascending: false })
      .limit(50);

    const errorCount = count || 0;
    const shouldNotify = force || errorCount >= threshold;

    if (!shouldNotify) {
      return new Response(JSON.stringify({ ok: true, errors_found: errorCount, action: 'none', message: 'System healthy' }), {
        headers: { ...cors, 'Content-Type': 'application/json' },
      });
    }

    // Group errors by type and source
    const grouped: Record<string, any[]> = {};
    for (const e of (errors || [])) {
      const key = `${e.source}:${e.error_type}`;
      if (!grouped[key]) grouped[key] = [];
      grouped[key].push(e);
    }

    const summary = Object.entries(grouped).map(([key, errs]) =>
      `${key}: ${errs.length}x — "${(errs[0].message || '').slice(0, 100)}"`
    ).join('\n');

    let briefingCreated = false;
    let obsidianWritten = false;

    // 1. Create briefing notification
    if (notify.includes('briefing')) {
      await supa.from('briefings').insert({
        briefing_type: 'debug',
        headline: `⚠️ Debug Agent: ${errorCount} error${errorCount !== 1 ? 's' : ''} detected`,
        preview: summary.slice(0, 300),
        content: `# Debug Report\n\n**Errors in last ${force ? '24 hours' : 'hour'}:** ${errorCount}\n\n## Breakdown\n\n${summary}\n\n## Action Required\nReview errors in Supabase → jarvis_errors table. No auto-fixes applied (sandbox-first policy).`,
        created_at: new Date().toISOString(),
      });
      briefingCreated = true;
    }

    // 2. Write to Obsidian
    if (notify.includes('obsidian') && anthropicKey) {
      const githubToken = Deno.env.get('GITHUB_TOKEN') || '';
      const githubRepo = Deno.env.get('GITHUB_OBSIDIAN_REPO') || '';
      if (githubToken && githubRepo) {
        const date = new Date().toISOString().slice(0, 10);
        const fileName = `Debug/${date}-error-report.md`;
        const content = `# Debug Report — ${date}\n\n**Total errors:** ${errorCount}\n**Window:** ${force ? '24 hours' : '1 hour'}\n**Threshold:** ${threshold}\n\n## Error Breakdown\n\n${summary}\n\n## Raw Errors (last 10)\n\n${(errors || []).slice(0, 10).map((e: any) =>
          `### ${e.source} | ${e.error_type}\n- Message: ${e.message}\n- Time: ${e.created_at}\n- Context: ${JSON.stringify(e.context || {}).slice(0, 200)}`
        ).join('\n\n')}\n\n---\n*Generated by JARVIS Debug Agent. No auto-fixes applied.*\n`;

        const encodedContent = btoa(unescape(encodeURIComponent(content)));
        const apiUrl = `https://api.github.com/repos/${githubRepo}/contents/${fileName}`;
        await fetch(apiUrl, {
          method: 'PUT',
          headers: {
            'Authorization': `token ${githubToken}`,
            'Content-Type': 'application/json',
            'User-Agent': 'JARVIS/4.0',
          },
          body: JSON.stringify({
            message: `JARVIS Debug: ${errorCount} errors — ${date}`,
            content: encodedContent,
            committer: { name: 'JARVIS Debug Agent', email: 'debug@jarvis.ai' },
          }),
        });
        obsidianWritten = true;
      }
    }

    return new Response(JSON.stringify({
      ok: true,
      errors_found: errorCount,
      briefing_created: briefingCreated,
      obsidian_written: obsidianWritten,
      summary: summary.slice(0, 500),
    }), { headers: { ...cors, 'Content-Type': 'application/json' } });

  } catch (e) {
    return new Response(JSON.stringify({ ok: false, error: e.message }), {
      status: 500, headers: { ...cors, 'Content-Type': 'application/json' },
    });
  }
});
